$("#ios-download-menu").hide();
$("#android-download-menu").hide();
$(document).ready(function(){
  $("#ios-button").click(function(){
    $("#android").addClass("android2")
    $("#android").removeClass("android")
    $("#android").removeClass("android3")
    $("#ios").addClass("ios3")
    $("#ios").removeClass("ios")
    $("#ios").removeClass("ios2")
    $("#ios-button").addClass("ios-button")
    $("#android-button").addClass("android-button2")
    $("#android-button").removeClass("android-button")
    $("#ios-download-menu").delay(500).show(500);
    $("#android-download-menu").hide();
    $("#ios-button").hide()
    $("#android-button").show()
  });
  $("#android-button").click(function(){
    $("#ios").addClass("ios2")
    $("#ios").removeClass("ios")
    $("#ios").removeClass("ios3")
    $("#android").addClass("android3")
    $("#android").removeClass("android")
    $("#android").removeClass("android2")
    $("#android-button").addClass("android-button")
    $("#ios-button").addClass("ios-button2")
    $("#ios-button").removeClass("ios-button")
    $("#android-download-menu").delay(500).show(500);
    $("#ios-download-menu").hide();
    $("#android-button").hide()
    $("#ios-button").show()
  });
  $("#close1").click(function(){
    $("#ios-download-menu").hide()
    $("#android-download-menu").hide()
    $("#ios-button").show()
    $("#android-button").show()
    $("#ios").addClass("ios")
    $("#android").addClass("android")
    $("#ios-button").addClass("ios-button")
    $("#android-button").addClass("android-button")
    $("#ios-button").removeClass("ios-button2")
    $("#android-button").removeClass("android-button2")
  });
  $("#close2").click(function(){
    $("#ios-download-menu").hide()
    $("#android-download-menu").hide()
    $("#ios-button").show()
    $("#android-button").show()
    $("#ios").addClass("ios")
    $("#android").addClass("android")
    $("#ios-button").addClass("ios-button")
    $("#android-button").addClass("android-button")
    $("#ios-button").removeClass("ios-button2")
    $("#android-button").removeClass("android-button2")
  });
});
